# Álgebra linear com o pacote Python NumPy

O [NumPy](https://numpy.org/) é um pacote Python que oferece estruturas de dados com características de vetores no $R^n$ e algoritmos para computação científica.  Esta introdução visa a dar os conhecimentos fundamentais do pacote para seu uso posterior em diferentes aplicações.[^1]

NumPy opera realizando todas as operações sobre vetores coordenada a coordenada numa operação que denomina [Broadcasting](https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting).

[^1]: As vantagens de usar NumPy em relação a escrever um código Python puro são mostradas [aqui](https://numpy.org/doc/stable/user/whatisnumpy.html)



Para usar a biblioteca NumPy, é preciso instalá-la, usando o conda ou o pip.[2^]

[2^]:Veja detalhes de instalação [aqui](https://numpy.org/install/).  Depois de instalada, para invocar o NumPy, basta o usar o comando import como mostrado na:

**Listagem 1: importando o Numpy**

In [1]:
import numpy as np

Para citar o uso de NumPy em trabalhos científicos, use a chave Latex seguinte:

@Article{         harris2020array,

 title         = {Array programming with {NumPy}},
 
 author        = {Charles R. Harris and K. Jarrod Millman and St{\'{e}}fan J.
                 van der Walt and Ralf Gommers and Pauli Virtanen and David
                 Cournapeau and Eric Wieser and Julian Taylor and Sebastian
                 Berg and Nathaniel J. Smith and Robert Kern and Matti Picus
                 and Stephan Hoyer and Marten H. van Kerkwijk and Matthew
                 Brett and Allan Haldane and Jaime Fern{\'{a}}ndez del
                 R{\'{i}}o and Mark Wiebe and Pearu Peterson and Pierre
                 G{\'{e}}rard-Marchant and Kevin Sheppard and Tyler Reddy and
                 Warren Weckesser and Hameer Abbasi and Christoph Gohlke and
                 Travis E. Oliphant},
                 
 year          = {2020},
 
 month         = sep,
 
 journal       = {Nature},
 
 volume        = {585},
 
 number        = {7825},
 
 pages         = {357--362},
 
 doi           = {10.1038/s41586-020-2649-2},
 
 publisher     = {Springer Science and Business Media {LLC}},
 
 url           = {https://doi.org/10.1038/s41586-020-2649-2}
}
    
 Para mais detalhes, ver [Citing NumPy](https://numpy.org/citing-numpy/).   


## A estrutura de dados fundamental: ndarray

Um ndarray é um arranjo multidimensional de valores de mesmo tipo de dado indexados por uma tupla de inteiros não negativos.  As dimensões desta tabela são chamadas de *axes*.


Na condição de objeto Python, o ndarray caracteriza-se por ter seus métodos definidos em linguagem compilada (C/C++ ou Fortran) para fins de melhoria de desempenho.

A estrutura ndarray possui um tamanho fixo na sua criação, diferindo-a das listas em Python, que podem ser ampliadas ou reduzidas em tempo de execução.

Para instanciar um ndarray, utiliza-se a função (método construtor) *np.array(x)* onde x é uma lista Python como mostrado na:

**Listagem 2: instanciando um objeto ndarray de um eixo (axis)**

In [12]:
# Em termos de álgebra linear, trata-se de um vetor linha 1 X 3
import numpy as np
a = np.array([1,2,3])
print(f"O número de eixos do ndarray a é igual a {a.ndim}")
print(f'O formato do vetor a é {a.shape}')

O número de eixos do ndarray a é igual a 1
O formato do vetor a é (3,)


**Listagem 3: instanciando um ndarray de dois axes**

In [14]:
# Em termos de álgebra linear, trata-se de uma matriz de dimensões 2 X 3
b = np.array([[1., 0.,0.], [0.,1.,2.]])
print(f"O número de eixos do ndarray b é igual a {b.ndim}")
print(f'O formato da matriz b é {b.shape}')

O número de eixos do ndarray b é igual a 2
O formato da matriz b é (2, 3)


Os principais atributos de um objeto ndarray são:

1. ndarray.ndim - fornece o número de eixos
2. ndarray.shape - fornece as dimensões do array
3. ndarray.size - número total de elementos do array
4. ndarray.dtype - é um objeto contendo o tipo de dado dos elementos do ndarray
5. ndarray.itemsize - número de bytes de cada elemento do ndarray
6. ndarray.data - região da memória onde estão armazenados os dados do ndarray (buffer de memória)

Considere a:

**Listagem 4: script para o exemplo do [Quickstart: an example](https://numpy.org/doc/stable/user/quickstart.html#an-example)**

In [26]:
import numpy as np

a = np.arange(15).reshape(3,5)
print(f'A matriz a é igual a: \n')
print(a)
print(f'\nO formato da matriz a é igual a {a.shape}.')
print(f'\nA matriz a tem {a.ndim} axes.')
print(f'\nO tipo de dados da matriz a é {a.dtype.name}')
print(f'\nO numero de bytes de cada elemento de ndarray a é igual {a.itemsize}')
print(f'\nO numero de elementos do ndarray a é igual {a.size}')
print(f'\nO tipo (classe) de a é {type(a)}')


A matriz a é igual a: 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

O formato da matriz a é igual a (3, 5).

A matriz a tem 2 axes.

O tipo de dados da matriz a é int32

O numero de bytes de cada elemento de ndarray a é igual 4

O numero de elementos do ndarray a é igual 15

O tipo (classe) de a é <class 'numpy.ndarray'>


**Listagem 5: exemplos de formas alternativas de instanciar ndarrays** 

In [30]:
# Instanciando um ndarray de números complexos

c = np.array([[1,2], [3,4]], dtype = complex)
print(c)

d = np.array([[1+1.j,2-3.j],[3-1.j,4-5.j]])
print(d)



[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]
[[1.+1.j 2.-3.j]
 [3.-1.j 4.-5.j]]


In [37]:
# Observe que se utiliza a notação 2 + 2j nativa de Python

e = 2 +2j
print(e)
print('\n')
f = np.array([[2+2j, 3+1j], [2+2j, 3+1j]], dtype=complex)
print(f)

(2+2j)


[[2.+2.j 3.+1.j]
 [2.+2.j 3.+1.j]]


In [41]:
# Contruindo um ndarray de zeros
# Observe que é preciso passar uma tupla Python com as dimensões do ndarray de zeros.
print(np.zeros((3,4)))


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [42]:
# O tipo de dados padrão para ndarrays é float64, mas pode ser alterado com o atributo dtype

print(np.ones((2,3,4), dtype = np.int16))

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


**Listagem 6: criando uma sequência de números**

Para criar um ndarray formado por uma sequência de números , utiliza-se a função np.arange((início, fim, passo)).  Note que a função é o método construtor do ndarray que recebe como parâmetro uma tupla Python com o início, o fim e o passo (distância entre dois elementos do array).

Observe também que, como sempre em Python, o último elemento não é incluído.

In [51]:
z = np.arange(10, 30, 5)
print(z)

print(type(z))

[10 15 20 25]
<class 'numpy.ndarray'>


In [52]:
z = np.arange(0, 2, 0.2)
print(z)
print(type(z))

[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8]
<class 'numpy.ndarray'>


**Observação**

Quando se quer ter certeza do número de elementos da sequência usa-se o método construtor linspace (início, fim, número de elementos no ndarray).

Note porém que, quando se usa a função linspace como método construtor do ndarray, **não apenas o início é incluído na sequência, mas também o fim é incluído.**

In [59]:
z = np.linspace(1,3, 9)
print(z)

[1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.  ]


**Listagem 7: NumPy tem a sua própria constante $\pi$**

In [57]:
# constante pi de Python
import math
print(math.pi)

3.141592653589793


In [58]:
# constante pi de Numpy
print(np.pi)

3.141592653589793


**Listagem 8: avaliando uma função em vários pontos**

In [63]:
# Avaliando o valor da função seno para ângulos de 0 a 2pi radianos
# nos pontos 0, 45, 90, 135, 180, 225, 270, 315 e 360 graus.

z = np.linspace(0,2*np.pi, 9)
seno = np.sin(z)
print(seno)

# Note o erro de aproximação decorrente do uso de números de ponto flutuante nos ângulos
# 180 graus e 360 graus (cujos senos são iguais a 0).


[ 0.00000000e+00  7.07106781e-01  1.00000000e+00  7.07106781e-01
  1.22464680e-16 -7.07106781e-01 -1.00000000e+00 -7.07106781e-01
 -2.44929360e-16]


## Operações com ndarrays

Matematicamente, ndarrays representam uma generalização a noção de vetor da álgebra linear conhecida como **[tensor](https://pt.wikipedia.org/wiki/Tensor#:~:text=Tensores%20s%C3%A3o%20entidades%20geom%C3%A9tricas%20introduzidas,a%20soma%20e%20o%20produto.)**.

Como já dito, as operações (aplicação de funções) com ndarrays se fazem coordenada a coordenada.  Como a adição coordenada a coordenada é trivial, iniciaremos com um exemplo de produto de dois ndarrays.

**Listagem 8: produto de ndarrays**






In [64]:
# Operação de produtos de tensores coordenada a coordenada.

A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])


print(A*B) 

[[2 0]
 [0 4]]


**Listagem 9: produto matricial**

In [65]:
# Usando método ndarray.dot()
A.dot(B)


array([[5, 4],
       [3, 4]])

In [67]:
# Usando o operador @ como representação ("açucar sintático") de ndarray.dot()

A @ B

array([[5, 4],
       [3, 4]])

**Listagem 10: operando com ndarrays de tipos distintos**

Neste caso, o tipo do ndarray resultante será aquele do tipo mais geral possível.  Isto é chamado upcasting.  Veja a seguir

In [75]:
a = np.ones(3, dtype=np.int32)
print(f'a = {a}')
print(f'O tipo de a é {a.dtype.name}\n')

b = np.linspace(0,np.pi,3)
print(f'b = {b}')
print(f'O tipo de b é {b.dtype.name}\n')

c = a + b
print(f'c = {a} + {b} = {c}')
print(c.dtype.name)

a = [1 1 1]
O tipo de a é int32

b = [0.         1.57079633 3.14159265]
O tipo de b é float64

c = [1 1 1] + [0.         1.57079633 3.14159265] = [1.         2.57079633 4.14159265]
float64


**Exercícios**

Continue fazendo o tutorial [Quickstart Guide](https://numpy.org/doc/stable/user/quickstart.html#universal-functions)